### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by cheesysam** [jefftriplett/rid.py#2]
Hi there,

Thanks for making this available. I've made some changes locally to get this working with Python3.

I was hoping to submit them and get the updated version on pip. Does this repo allow pushing branches? I don't seem to be able to push my branch.

Thanks
Sam

**Comment by cheesysam** [comment]
No worries, forked and PR'd :)

**Comment by jefftriplett** [comment]
@cheesysam thanks, I'll dust it off and push to pip this afternoon.

**Comment by jefftriplett** [comment]
@cheesysam updated and pushed to pypi. I'll try and finish up some notes later. Thanks for the nudge and PR again.
